project:
  type: book
  output-dir: docs

book:
  title: "R Programming... for analysts who aren't programmers!"
  author: "Albert Lee"
  date: "January 20, 2026"
  chapters:
    - index.qmd
    - 01_r4everyone.qmd
    - 02_r4datamanipulation.qmd
    - references.qmd
  sidebar:
    numbered: false

number-sections: false
    
crossref: 
  chapters: false

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

